---
- hosts: all
  gather_facts: False
  become: true
  
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      
    - name: Asegurarse que está git
      apt: pkg=git state=latest

    - name: Añadir repo de Atom
      raw: sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list' && apt-get update -y

    - name: instalar Atom
      apt: pkg=atom state=latest allow_unauthenticated=true

